import 'client.dart';
import 'invoice_template.dart';
import 'line_item.dart';
import 'partial_payment.dart';
import 'recurring_schedule.dart'; // for QuotationStatus
import 'custom_field.dart';

// partiallyPaid added at end (index 5) to preserve existing stored indexes 0-4
// pendingApproval added at end (index 6) to preserve existing stored indexes 0-5
enum InvoiceStatus { draft, sent, paid, overdue, cancelled, partiallyPaid, pendingApproval }

extension InvoiceStatusExt on InvoiceStatus {
  String get label {
    switch (this) {
      case InvoiceStatus.draft:
        return 'Draft';
      case InvoiceStatus.sent:
        return 'Sent';
      case InvoiceStatus.paid:
        return 'Paid';
      case InvoiceStatus.overdue:
        return 'Overdue';
      case InvoiceStatus.cancelled:
        return 'Cancelled';
      case InvoiceStatus.partiallyPaid:
        return 'Partial';
      case InvoiceStatus.pendingApproval:
        return 'Pending';
    }
  }
}

class Invoice {
  final String id;
  String invoiceNumber;
  Client? client;
  DateTime invoiceDate;
  DateTime dueDate;
  List<LineItem> items;
  InvoiceStatus status;
  String? notes;
  String? terms;
  double globalDiscountPercent;
  double globalDiscountFlat;
  String currency;
  DateTime createdAt;
  InvoiceTemplate? template;
  String? paymentMethodId;
  String? paymentMethodName;
  String? subject;
  List<PartialPayment> payments;
  String? placeOfSupply;
  bool reverseCharge;

  /// When true, the PDF shows every recorded payment and the outstanding
  /// balance beneath the Grand Total. Off by default — client's choice.
  bool showPaymentsOnInvoice;

  /// When true this document is a Quotation/Estimate, not a final invoice.
  /// The PDF header reads "QUOTATION" and the status uses [quotationStatus].
  bool isQuotation;
  QuotationStatus? quotationStatus;

  /// When true this is a Credit Note issued against [creditNoteLinkedInvoiceId].
  /// The PDF header reads "CREDIT NOTE".
  bool isCreditNote;
  String? creditNoteLinkedInvoiceId;

  /// When true this document is a Delivery Challan (goods despatched before
  /// invoice is raised). The PDF header reads "DELIVERY CHALLAN".
  bool isDeliveryChallan;
  /// Set when this challan is converted to a formal invoice.
  String? challanLinkedInvoiceId;

  // ── E-Invoice (IRP / IRN) ─────────────────────────────────────────────────
  /// Invoice Reference Number issued by the IRP portal (NIC).
  String? irn;
  /// Acknowledgement number returned by the IRP.
  String? ackNo;
  /// Acknowledgement date-time returned by the IRP.
  DateTime? ackDt;
  /// Signed QR code payload (base64) for printing on the PDF.
  String? signedQRCode;

  // ── E-Way Bill ────────────────────────────────────────────────────────────
  String? ewayBillNo;
  DateTime? ewayBillDate;
  DateTime? ewayBillValidTill;

  /// True once stock has been deducted for this invoice.
  /// Prevents double-deduction if status is changed multiple times.
  bool stockDeducted;

  /// User-defined key-value pairs shown on the invoice (PO Number, Project, etc.)
  List<CustomField> customFields;

  /// Optional: show the grand total converted into this second currency on the PDF.
  /// null means the feature is off for this invoice.
  String? secondaryCurrency;

  /// The frozen exchange rate at the time the invoice was saved.
  /// Semantics: 1 unit of [currency] = [secondaryExchangeRate] units of [secondaryCurrency].
  /// Stored so the PDF always shows a consistent converted amount regardless of later rate changes.
  double? secondaryExchangeRate;

  /// Set when this invoice was auto-generated by a [RecurringSchedule].
  String? recurringScheduleId;

  // Approval workflow fields
  /// Email of the approver (set when approved or rejected).
  String? approvedBy;
  DateTime? approvedAt;
  /// Rejection reason or approval comment.
  String? approvalNotes;

  // Audit fields — stamped by AppProvider on every create/edit
  String? createdBy;
  String? lastEditedBy;
  DateTime? lastEditedAt;

  /// Which shop created this document. null = owner's primary shop or legacy.
  String? shopId;

  /// True when this document was created offline and has not yet received a
  /// real series number from the Firestore atomic counter.
  /// Cleared to false once [SeriesCounterService.assignPendingNumbers] runs
  /// successfully during the next Drive push.
  bool pendingNumber;

  Invoice({
    required this.id,
    required this.invoiceNumber,
    this.client,
    required this.invoiceDate,
    required this.dueDate,
    List<LineItem>? items,
    this.status = InvoiceStatus.draft,
    this.subject,
    this.notes,
    this.terms,
    this.globalDiscountPercent = 0,
    this.globalDiscountFlat = 0,
    this.currency = 'INR',
    DateTime? createdAt,
    this.template,
    this.paymentMethodId,
    this.paymentMethodName,
    List<PartialPayment>? payments,
    this.placeOfSupply,
    this.reverseCharge = false,
    this.showPaymentsOnInvoice = false,
    this.isQuotation = false,
    this.quotationStatus,
    this.recurringScheduleId,
    this.isCreditNote = false,
    this.creditNoteLinkedInvoiceId,
    this.isDeliveryChallan = false,
    this.challanLinkedInvoiceId,
    this.stockDeducted = false,
    List<CustomField>? customFields,
    this.approvedBy,
    this.approvedAt,
    this.approvalNotes,
    this.createdBy,
    this.lastEditedBy,
    this.lastEditedAt,
    this.shopId,
    this.pendingNumber = false,
    this.irn,
    this.ackNo,
    this.ackDt,
    this.signedQRCode,
    this.ewayBillNo,
    this.ewayBillDate,
    this.ewayBillValidTill,
    this.secondaryCurrency,
    this.secondaryExchangeRate,
  })  : items = items ?? [],
        payments = payments ?? [],
        customFields = customFields ?? [],
        createdAt = createdAt ?? DateTime.now();

  double get subtotal => items.fold(0, (sum, item) => sum + item.subtotal);
  double get totalDiscount =>
      items.fold(0.0, (sum, item) => sum + item.discountAmount) +
      subtotal * (globalDiscountPercent / 100) +
      globalDiscountFlat;
  double get totalTax => items.fold(0, (sum, item) => sum + item.taxAmount);
  double get grandTotal => subtotal - totalDiscount + totalTax;

  /// Total amount effectively settled: cash received + TDS credit.
  /// TDS (Tax Deducted at Source) is a tax credit recoverable from the
  /// government, so it counts toward settling the invoice.
  double get amountPaid =>
      payments.fold(0.0, (sum, p) => sum + p.amount + (p.tdsAmount ?? 0));

  /// Cash actually received (excludes TDS credit).
  double get cashReceived =>
      payments.fold(0.0, (sum, p) => sum + p.amount);

  /// Total TDS deducted across all payments.
  double get totalTdsDeducted =>
      payments.fold(0.0, (sum, p) => sum + (p.tdsAmount ?? 0));
  double get amountRemaining => (grandTotal - amountPaid).clamp(0.0, double.infinity);

  bool get isOverdue =>
      status != InvoiceStatus.paid &&
      status != InvoiceStatus.cancelled &&
      dueDate.isBefore(DateTime.now());

  Invoice copy() => Invoice(
        id: id,
        invoiceNumber: invoiceNumber,
        client: client,
        invoiceDate: invoiceDate,
        dueDate: dueDate,
        items: items.map((e) => e.copy()).toList(),
        status: status,
        subject: subject,
        notes: notes,
        terms: terms,
        globalDiscountPercent: globalDiscountPercent,
        globalDiscountFlat: globalDiscountFlat,
        currency: currency,
        createdAt: createdAt,
        template: template,
        paymentMethodId: paymentMethodId,
        paymentMethodName: paymentMethodName,
        payments: List.from(payments),
        placeOfSupply: placeOfSupply,
        reverseCharge: reverseCharge,
        showPaymentsOnInvoice: showPaymentsOnInvoice,
        isQuotation: isQuotation,
        quotationStatus: quotationStatus,
        recurringScheduleId: recurringScheduleId,
        isCreditNote: isCreditNote,
        creditNoteLinkedInvoiceId: creditNoteLinkedInvoiceId,
        isDeliveryChallan: isDeliveryChallan,
        challanLinkedInvoiceId: challanLinkedInvoiceId,
        customFields: customFields.map((f) => f.copy()).toList(),
        approvedBy: approvedBy,
        approvedAt: approvedAt,
        approvalNotes: approvalNotes,
        createdBy: createdBy,
        lastEditedBy: lastEditedBy,
        lastEditedAt: lastEditedAt,
        shopId: shopId,
        pendingNumber: pendingNumber,
        irn: irn,
        ackNo: ackNo,
        ackDt: ackDt,
        signedQRCode: signedQRCode,
        ewayBillNo: ewayBillNo,
        ewayBillDate: ewayBillDate,
        ewayBillValidTill: ewayBillValidTill,
        secondaryCurrency: secondaryCurrency,
        secondaryExchangeRate: secondaryExchangeRate,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'invoiceNumber': invoiceNumber,
        'client': client?.toJson(),
        'invoiceDate': invoiceDate.toIso8601String(),
        'dueDate': dueDate.toIso8601String(),
        'items': items.map((e) => e.toJson()).toList(),
        'status': status.index,
        'subject': subject,
        'notes': notes,
        'terms': terms,
        'globalDiscountPercent': globalDiscountPercent,
        'globalDiscountFlat': globalDiscountFlat,
        'currency': currency,
        'createdAt': createdAt.toIso8601String(),
        'template': template?.name,
        'paymentMethodId': paymentMethodId,
        'paymentMethodName': paymentMethodName,
        'payments': payments.map((p) => p.toJson()).toList(),
        'placeOfSupply': placeOfSupply,
        'reverseCharge': reverseCharge,
        'showPaymentsOnInvoice': showPaymentsOnInvoice,
        'isQuotation': isQuotation,
        'quotationStatus': quotationStatus?.name,
        'recurringScheduleId': recurringScheduleId,
        'isCreditNote': isCreditNote,
        'creditNoteLinkedInvoiceId': creditNoteLinkedInvoiceId,
        'isDeliveryChallan': isDeliveryChallan,
        'challanLinkedInvoiceId': challanLinkedInvoiceId,
        'stockDeducted': stockDeducted,
        'customFields': customFields.map((f) => f.toJson()).toList(),
        'approvedBy': approvedBy,
        'approvedAt': approvedAt?.toIso8601String(),
        'approvalNotes': approvalNotes,
        'createdBy': createdBy,
        'lastEditedBy': lastEditedBy,
        if (shopId != null) 'shopId': shopId,
        'lastEditedAt': lastEditedAt?.toIso8601String(),
        'pendingNumber': pendingNumber,
        'irn': irn,
        'ackNo': ackNo,
        'ackDt': ackDt?.toIso8601String(),
        'signedQRCode': signedQRCode,
        'ewayBillNo': ewayBillNo,
        'ewayBillDate': ewayBillDate?.toIso8601String(),
        'ewayBillValidTill': ewayBillValidTill?.toIso8601String(),
        'secondaryCurrency': secondaryCurrency,
        'secondaryExchangeRate': secondaryExchangeRate,
      };

  factory Invoice.fromJson(Map<String, dynamic> json) => Invoice(
        id: json['id'],
        invoiceNumber: json['invoiceNumber'],
        client:
            json['client'] != null ? Client.fromJson(json['client']) : null,
        invoiceDate: DateTime.parse(json['invoiceDate']),
        dueDate: DateTime.parse(json['dueDate']),
        items: (json['items'] as List)
            .map((e) => LineItem.fromJson(e))
            .toList(),
        status: InvoiceStatus.values[json['status'] ?? 0],
        subject: json['subject'],
        notes: json['notes'],
        terms: json['terms'],
        globalDiscountPercent:
            (json['globalDiscountPercent'] as num?)?.toDouble() ?? 0,
        globalDiscountFlat:
            (json['globalDiscountFlat'] as num?)?.toDouble() ?? 0,
        currency: json['currency'] ?? 'INR',
        createdAt: json['createdAt'] != null
            ? DateTime.parse(json['createdAt'])
            : DateTime.now(),
        template: json['template'] != null
            ? InvoiceTemplate.values.firstWhere(
                (e) => e.name == json['template'],
                orElse: () => InvoiceTemplate.classic)
            : null,
        paymentMethodId: json['paymentMethodId'],
        paymentMethodName: json['paymentMethodName'],
        payments: (json['payments'] as List<dynamic>?)
                ?.map((e) => PartialPayment.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
        placeOfSupply: json['placeOfSupply'] as String?,
        reverseCharge: json['reverseCharge'] as bool? ?? false,
        showPaymentsOnInvoice: json['showPaymentsOnInvoice'] as bool? ?? false,
        isQuotation: json['isQuotation'] as bool? ?? false,
        quotationStatus: json['quotationStatus'] != null
            ? QuotationStatus.values.firstWhere(
                (s) => s.name == json['quotationStatus'],
                orElse: () => QuotationStatus.draft)
            : null,
        recurringScheduleId: json['recurringScheduleId'] as String?,
        isCreditNote: json['isCreditNote'] as bool? ?? false,
        creditNoteLinkedInvoiceId: json['creditNoteLinkedInvoiceId'] as String?,
        isDeliveryChallan: json['isDeliveryChallan'] as bool? ?? false,
        challanLinkedInvoiceId: json['challanLinkedInvoiceId'] as String?,
        stockDeducted: json['stockDeducted'] as bool? ?? false,
        customFields: (json['customFields'] as List<dynamic>?)
                ?.map((e) =>
                    CustomField.fromJson(e as Map<String, dynamic>))
                .toList() ??
            [],
        approvedBy: json['approvedBy'] as String?,
        approvedAt: json['approvedAt'] != null
            ? DateTime.tryParse(json['approvedAt'] as String)
            : null,
        approvalNotes: json['approvalNotes'] as String?,
        createdBy: json['createdBy'] as String?,
        lastEditedBy: json['lastEditedBy'] as String?,
        shopId: json['shopId'] as String?,
        lastEditedAt: json['lastEditedAt'] != null
            ? DateTime.tryParse(json['lastEditedAt'] as String)
            : null,
        pendingNumber: json['pendingNumber'] as bool? ?? false,
        irn: json['irn'] as String?,
        ackNo: json['ackNo'] as String?,
        ackDt: json['ackDt'] != null
            ? DateTime.tryParse(json['ackDt'] as String)
            : null,
        signedQRCode: json['signedQRCode'] as String?,
        ewayBillNo: json['ewayBillNo'] as String?,
        ewayBillDate: json['ewayBillDate'] != null
            ? DateTime.tryParse(json['ewayBillDate'] as String)
            : null,
        ewayBillValidTill: json['ewayBillValidTill'] != null
            ? DateTime.tryParse(json['ewayBillValidTill'] as String)
            : null,
        secondaryCurrency: json['secondaryCurrency'] as String?,
        secondaryExchangeRate: (json['secondaryExchangeRate'] as num?)?.toDouble(),
      );
}
